# Generated by Django 5.2.6 on 2025-09-20 12:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('is_marked', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='CleanedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('language', models.CharField(max_length=50)),
                ('hazard_type', models.CharField(choices=[('FLOOD', 'flood'), ('TSUNAMI', 'tsunami'), ('EARTHQUAKE', 'earthquake'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('confidence', models.FloatField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('locations', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326)),
                ('sentiment', models.CharField(max_length=20)),
                ('urgency_score', models.FloatField()),
                ('source', models.CharField(blank=True, max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('original_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_report', to='reports.reported')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
