# Generated by Django 5.2.5 on 2025-09-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_reported_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleanedreport",
            name="hazard_type",
            field=models.CharField(
                choices=[
                    ("TSUNAMI", "tsunami"),
                    ("FLOOD", "flood"),
                    ("FLASH_FLOOD", "flash_flood"),
                    ("HIGH_WAVES", "high_waves"),
                    ("STORM_SURGE", "storm_surge"),
                    ("WATER_SPOUT", "water_spout"),
                    ("DAM_BURST", "dam_burst"),
                    ("RIVER_OVERFLOW", "river_overflow"),
                    ("COASTAL_EROSION", "coastal_erosion"),
                    ("KING_TIDE", "king_tide"),
                    ("SEICHE", "seiche"),
                    ("CYCLONE", "cyclone"),
                    ("EARTHQUAKE", "earthquake"),
                    ("WILDFIRE", "wildfire"),
                    ("LANDSLIDE", "landslide"),
                    ("UNKNOWN", "unknown"),
                    ("OTHER", "Other"),
                ],
                default="UNKNOWN",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="cleanedreport",
            name="severity",
            field=models.CharField(
                choices=[
                    ("LOW", "low"),
                    ("MEDIUM", "medium"),
                    ("HIGH", "high"),
                    ("CRITICAL", "critical"),
                ],
                default="LOW",
                max_length=10,
            ),
        ),
    ]
